# Generated by Django 2.1 on 2019-04-30 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_featuredproject_feature_date'),
        ('project', '0010_auto_20190429_1734'),
    ]

    operations = [
    ]
