# Generated by Django 2.1 on 2019-04-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190425_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='DOB',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.CharField(max_length=20),
        ),
    ]
