# Generated by Django 2.1 on 2019-04-25 12:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190425_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='DOB',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
