# Generated by Django 2.1 on 2019-04-25 12:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_customuser_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='DOB',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
