# Generated by Django 2.1 on 2019-04-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20190427_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='FB',
            field=models.URLField(max_length=100),
        ),
    ]
